<div class="container">
   <div class="row">
      <h1>Blog</h1>
      
      <? foreach($posts as $post) : ?>
      <a href="/blog/<?= $post['id'] ?>">
         <div class="post">
            <span><?= $post['title'] ?></span>
            <? $leader = $post['leader_medium'] ?: $post['leader'] ?>
            <img src="<?= $leader ?>">
         </div>
      </a>
   <? endforeach ?>
   </div>
   <footer class="content">
      <ul class="meta">
         <? if ($previousPage) : ?>
            <li><a href="/blog?p=<?= $previousPage ?>"><i class="fa fa-chevron-left"></i></a></li>
         <? endif ?>
         <? if ($nextPage) : ?>
            <li><a href="/blog?p=<?= $nextPage ?>"><i class="fa fa-chevron-right"></i></a></li>
         <? endif ?>
      </ul>
   </footer>
</div>
