<div class="container">
   <div class="row">
      <header class="content">
         <h1><?= $post->title ?></h1>
         <ul class="meta">
            <li><?= date("F jS, Y", $post->date) ?></li>
         </ul>
      </header>
      <div class="content">
         <?= $post->getRendered() ?>
      </div>
      <? if ($user) : ?>
         <ul class="meta">
            <li><a href="/edit/<?= $post->id ?>"><i class="fa fa-pencil"></i></a></li>
         </ul>
      <? endif ?>
   </div>
</div>
