<div class="container">
   <div class="row">
      <header class="content">
         <h1><?= $post->title ?></h1>
         <div class="post">
            <? if ($user) : ?>
            <span><a href="/edit/<?= $post->id ?>"><i class="fa fa-pencil"></i></a></span>
            <? endif ?>
            <? if ($post->leader) : ?>
            <img src="<?= MediaManager::URI($post->leader) ?>">
            <? endif ?>
         </div>
         <ul class="meta">
            <li><?= date("F jS, Y", $post->date) ?></li>
         </ul>
      </header>
      <div class="content">
         <?= $post->getRendered() ?>
      </div>
   </div>
</div>
