<div class="container">
   <div id="postTitle">
      <?= $post ? $post->title  : '' ?>
   </div>
   <hr>
   <div class="well" id="post-well">
      <?= $post ? $post->body  : '' ?>
   </div>
   <div class="form-group">
      <div class="pull-left">
         <input type="checkbox" id="publishedCheckbox" 
            <?= $post ? ($post->published ? 'checked' : '') : '' ?>> Published
      </div>
      <div class="pull-right">
         <i class="fa fa-check-circle-o hide" id="checkMark"></i> 
         <i class="fa fa-times hide" id="xMark"></i> 
         <button type="button" class="btn btn-info" id="saveButton">Save</button>
      </div>
   </div>
</div>
