<div class="container">
   <div class="row">
      <header class="content">
         <h1><?= $gallery->row['title'] ?></h1>
         <div class="post">
            <? if ($user) :?>
            <span><a id="addImageButton"><i class="fa fa-plus"></i></a></span>
            <? endif ?>
            <? if ($gallery->row['src']) : ?>
            <img src="<?= $gallery->row['src'] ?>">
            <? endif ?>
         </div>
      </header>
      <div class="content" id="masonryContainer">
         <? foreach($gallery->entries as $photo): ?>
            <div class="brick"><img src="<?= $photo['src'] ?>" alt="<?= $photo['caption'] ?>"></div>
         <? endforeach ?>
      </div>
   </div>
</div>
