<div class="container">
   <div class="row">
      <header class="content leader centered">
         <h1>Scott Vanderlind</h2>
         <img class="outline" src="/Templates/scott/img/outline.png">
      </header>
      <div class="content centered">
         <ul class="links">
            <li><a href="/blog/">Projects</a></li>
            <li><a href="/about/">About</a></li>
         </ul>
      </div>
   </div>
</div>
