<div class="container">
   <div class="row">
      <div class="col-md-4 col-md-offset-4">
         <form class="form-signin" role="form" method="POST">
            <h2 class="form-signin-heading">Please sign in</h2>
            <div class="form-group">
               <input type="username" class="form-control" placeholder="Username" required="" autofocus="" name="username">
            </div>
            <div class="form-group">
               <input type="password" class="form-control" placeholder="Password" required="" name="password">
            </div>
            <label class="checkbox">
               <input type="checkbox" value="remember-me"> Remember me
            </label>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
         </form>
      </div>
   </div>
</div>
