<div class="container">
   <div class="row">
      <header class="content">
         <h1><?= $post->title ?></h1>
         <div class="post">
            <span id="changeLeaderButton"><i class="fa fa-picture-o"></i></span>
            <img data-medid="<?= $post->leader ?>" src="<?= MediaManager::URI($post->leader) ?>" id="leaderImage">
         </div>
      </header>
      <br>
      <div class="content">
         <ul class="buttonBar">
            <li id="undoButton"><i class="fa fa-reply"></i></li>
            <li id="redoButton"><i class="fa fa-share"></i></li>
            <li id="insertPhotoButton"><i class="fa fa-picture-o"></i></li>
         </ul>

         <textarea name="body" id="bodyInput" cols="100" rows="20"><?= $post->body ?></textarea>
         <br>
         <input type="checkbox" id="publishedCheckbox" <?= $post->published ? 'checked' : '' ?>>
         <button id="saveButton">save</button>

      </div>
   </div>
</div>
