<div class="container">
   <div class="row">
      <div class="content centered">
         <h3>Take a selfie!</h3>
         <div id="viewfinder" class="camera"></div>
         <div id="release" class="shutter"><i class="fa fa-camera-retro"></i></div>
         <div id="save" class="shutter"><i class="fa fa-floppy-o"></i></div>
         <img id="preview" class="camera">
      </div>
   </div>
</div>
