<div class="container">
   <div class="row">
      <div class="content">
         <h2>signup</h2>
          <form id="signupForm">
            <input type="text" name="firstname" placeholder="first name"> 
            <input type="text" name="lastname" placeholder="last name"> 
            <input type="text" name="username" placeholder="desired username"> 
            <input type="text" name="email" placeholder="email address">
            <input type="password" name="password" placeholder="password">
            <button type="submit" class="button">Sign up!</button>
         </form>
      </div>
   </div>
</div>
